### ISSUE TITLE
[BUG] - IsADirectoryError

### ISSUE THREAD

**Issue by nezbite** [YourKalamity/lazy-dsi-file-downloader#10]
**Describe the bug**
Running the python version on macOS with python3 results in an error when downloading. The error states that `lazy-dsi-file-downloader-tmp` is a directory (which it is).

**To Reproduce**
Run `python3 main.py` on macOS

**Desktop (please complete the following information):**
- OS: macOS Big Sur 11.0.1
- Python version: 3.9.2

**Additional context**
I tried using the .dmg version, but that one has issues using `Darwin/7za` (FileNotFound). I figured I might aswell use the uncompiled version since that one has the file I needed included.

**Comment by YourKalamity** [comment]
Can you show the full traceback error?

**Comment by nezbite** [comment]
```
7-Zip found!
Memory Pit Downloaded
TWiLight Menu ++ Downloaded

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 33217738 bytes (32 MiB)

Extracting archive: /Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/lazy-dsi-file-downloader-tmp/TWiLightMenu-DSi.7z
--
Path = /Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/lazy-dsi-file-downloader-tmp/TWiLightMenu-DSi.7z
Type = 7z
Physical Size = 33217738
Headers Size = 10085
Method = LZMA2:24
Solid = +
Blocks = 1

Everything is Ok

Folders: 79
Files: 1001
Size:       70486920
Compressed: 33217738
TWiLight Menu ++ Extracted to /Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/lazy-dsi-file-downloader-tmp/
TWiLight  Menu ++ placed in /Volumes/NO NAME
DeadSkullzJr's Cheat Database downloaded
dumpTool downloaded
Unlaunch Downloaded
GodMode9i downloaded

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 176022 bytes (172 KiB)

Extracting archive: /Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/lazy-dsi-file-downloader-tmp/GodMode9i.7z
--
Path = /Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/lazy-dsi-file-downloader-tmp/GodMode9i.7z
Type = 7z
Physical Size = 176022
Headers Size = 203
Method = LZMA2:1536k
Solid = +
Blocks = 1


No files to process
Everything is Ok

Files: 0
Size:       0
Compressed: 176022
GodMode9i Extracted to /Volumes/NO NAME/roms/nds/
Downloading other homebrew...
Downloading JPN -> EUR DSi Patcher
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/main.py", line 319, in start
    downloadLocation = downloadFile(downloadlink, cwdtemp)
  File "/Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/main.py", line 44, in downloadFile
    open(downloadLocation, 'wb').write(r.content)
IsADirectoryError: [Errno 21] Is a directory: '/Users/daniel/Downloads/lazy-dsi-file-downloader-3.1.2-Python3/lazy-dsi-file-downloader-tmp/'
```

**Comment by nezbite** [comment]
I am just now trying this on Windows. The issue comes when selecting additional homebrew. When not selecting any, there is no error, even on macOS. I suspect it's the JPN -> EUR patcher from additional homebrew. Will test a bit and report back.

**Comment by nezbite** [comment]
So it's definitely the JPN -> EUR DSi Patcher. When selecting it, the last entry in the log from the python window says `Downloading JPN -> EUR DSi Patcher` and the IsADirectoryError is shown in the terminal.

**Comment by YourKalamity** [comment]
The DSi Language Patcher has been removed from `Additional Homebrew` until the releases are put on GitHub, where hopefully it won't error out on. Thanks for pointing this issue out.
