### ISSUE TITLE
[BUG] - PyInstaller Windows executable leads to DLL error with Py7zr

### ISSUE THREAD

**Issue by YourKalamity** [YourKalamity/lazy-dsi-file-downloader#14]
Current master branch with Py7zr (as an alternative to including 7z executables) throws an error after compiling and running.

`Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "py7zr\__init__.py", line 49, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "py7zr\py7zr.py", line 41, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "py7zr\archiveinfo.py", line 35, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "py7zr\compressor.py", line 32, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "ppmd\__init__.py", line 41, in <module>
ImportError: DLL load failed while importing _ppmd: %1 is not a valid Win32 application.
[20012] Failed to execute script main`

**To Reproduce**
1. Clone repo
2. Install PyInstaller
3. Run `  pyinstaller --onefile --add-data "certifi;certifi" --add-data "requests;requests" --add-data "urllib3;urllib3" --add-data "lazy.ico;." --add-data "chardet;chardet" --icon "lazy.ico" --console --name "lazy-dsi-file-downloader-master-Windows" main.py`
4. Run the created executable

**Expected behavior**
Application should launch like normal

**Desktop (please complete the following information):**
 - OS: Windows 10
 - May require testing on other platforms

**Comment by YourKalamity** [comment]
#19 Fixed it
