### ISSUE TITLE
Doesn't account for missing trailing slash

### ISSUE THREAD

**Issue by Poccket** [YourKalamity/lazy-dsi-file-downloader#4]
I'm running the python script through Linux, and when selecting the folder of extraction, if there's no trailing '/' in the text box then it will freeze up halfway through because it attempts to extract to `/media/user/sddumpTool.nds` instead of `/media/user/sd/dumpTool.nds`

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 232, in start
    downloadLocation = downloadFile(getLatestGitHub('zoogie/dumpTool', 0), directory)
  File "main.py", line 41, in downloadFile
    open(downloadLocation, 'wb').write(r.content)
PermissionError: [Errno 13] Permission denied: '/media/rilesmcgiles/3332-6630dumpTool.nds
```

**Comment by YourKalamity** [comment]
Thanks for pointing it out
